version: '3.8'

networks:
  mynet:
    external:
      name: mynet

services:
  registration:
    container_name: registration
    depends_on:
      - "postgersregistration"
    networks:
      - mynet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "60123:80"
      # - "9090:80"
    expose:
      - "80"
      # - "9090:80"
    environment:
      DB_CONNECTION_STRING: "Host=postgersregistration;Port=5432;Database=User_DB;Username=postgres;Password=159753"

  # webapinotes:
  #   image: webapinotes
  #   depends_on:
  #     - "postgers"
  #   build: 
  #     context: .
  #     dockerfile: WebNotesApi/Dockerfile
  #   ports:
  #     - "62305:80"
  #     # - "9090:80"
  #   environment:
  #     DB_CONNECTION_STRING: "Host=postgers;Port=5432;Database=Notes;Username=postgres;Password=159753"


  # postgers:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "159753"
  #     POSTGRES_DB: "Notes"

  postgersregistration:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "159753"
      POSTGRES_DB: "User_DB"
