version: '3.8'

# networks:
#   mynet:
#     external:
#       name: mynet

services:
  registration:
    container_name: registration
    depends_on:
      - "postgersregistration"
    # networks:
    #   - mynet
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "60123:80"
      # - "9090:80"
    # expose:
    #   - "80"
      # - "9090:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DB_CONNECTION_STRING: "Host=postgersregistration;Port=5432;Database=User_DB;Username=postgres;Password=159753"


  postgersregistration:
    image: postgres
    container_name: postgersregistration
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "159753"
      POSTGRES_DB: "User_DB"
